global:
  resolve_timeout: 2s
  slack_api_url: 'slack_chat_url'
route:
  receiver: 'slack-notifications'
  repeat_interval: 10s
  group_interval: 10s
  group_wait: 10s
receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#test_alerts_links'
  - send_resolved: true
    actions:
    - type: button
      text: Runbook
      url: '{{ template "slack.buttons.runbook" . }}'
    - type: button
      text: Query
      url: '{{ template "slack.buttons.query" . }}'
    - type: button
      text: Dashboard
      url: '{{ template "slack.buttons.dashboard" . }}'
    - type: button
      text: Logs
      url: '{{ template "slack.buttons.logs" . }}'
templates:
- /etc/alertmanager/*.tmpl
