global:
  resolve_timeout: 2s
  slack_api_url: ''
route:
  receiver: 'slack-notifications'
  repeat_interval: 10s
  group_interval: 10s
  group_wait: 10s
receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#test_alerts_links'
  - send_resolved: true
    actions:
    - type: button
      text: Runbook
      url: '{{ template "slack.buttons.runbook" . }}'
    - type: button
      text: Query
      url: '{{ template "slack.buttons.query" . }}'
    - type: button
      text: Dashboard
      url: '{{ template "slack.buttons.dashboard" . }}'
    - type: button
      text: Logs
      url: '{{ template "slack.buttons.logs" . }}'
templates:
- /etc/alertmanager/*.tmpl
#TELEGRAM
#global:
#  resolve_timeout: 1s
#receivers:
#- name: default-telegram
#  telegram_configs:
#  - api_url: https://api.telegram.org
#    bot_token: "2020614219:AAGY7TFbj2YkdQ5x7SySzcYb9tALWd0Ci80"
#    chat_id: 378250546
#    disable_notifications: false
#    http_config:
#      follow_redirects: true
#    send_resolved: true
#    parse_mode: ""
#route:
#  continue: false
#  group_by:
#  - job
#  group_interval: 1s
#  group_wait: 1s
#  receiver: default-telegram
#  repeat_interval: 1s
#  routes:
#  - receiver: default-telegram
#templates:
#- /etc/alertmanager/*.tmpl